version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_school
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_school
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - default

volumes:
  grafana-storage: